version: '3.1'
services:
  mysql:
    container_name: "mysql"
    image: "mysql:latest"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=bytewright
      - MYSQL_PASSWORD=bytewright
    ports:
      - "3306:3306"
    volumes:
      - "/data/mysql/8:/var/lib/mysql:rw"

  adminer:
    container_name: "mysql-adminer"
    image: adminer
    restart: always
    ports:
      - "33306:8080"

  mongodb:
    container_name: "mongodb"
    image: "mongo:4"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongodb:/data/db:rw"

  redis:
    container_name: "redis"
    image: "redis:5"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "/data/redis:/data:rw"

        #rabbitmq:
        #container_name: "rabbitmq"
        #image: "rabbitmq:3"
        #environment:
        #  - RABBITMQ_NODENAME=rqnode@byte-rabbit
        #  - RABBITMQ_DEFAULT_USER=bytewright
        #  - RABBITMQ_DEFAULT_PASS=bytewright
      #volumes:
      #- /data/rabbitmq:/var/lib/rabbitmq:rw
    #ports:
    # - "5672:5672"
    # - "15672:15672"

#  webserver-nginx:
#    container_name: "webserver-nginx"
#    image: "nginx:latest"
#    ports:
#     - "80:80"
#     - "443:443"
#    volumes:
#     - "./docker/nginx/webserver/conf-local/nginx:/etc/nginx/conf.d:ro"